//
// Copyright 2026 Stealth Software Technologies, Inc.
// SPDX-License-Identifier: Apache-2.0
//

mod failure_makes_receiver_ready;
mod parked_receive_resumes_at_arrival_without_intermediate_poll;
mod partial_receive_frees_prefix_capacity;
mod partial_receive_preserves_terminal_error;
mod readiness_wins_at_timeout;
mod receive_timeout_is_nonterminal;
mod receive_with_options_overrides_endpoint_timeout;
mod receive_with_options_times_out;
mod receive_work_advances_time_and_holds_activity;
mod receiving_timeout_is_configurable;
mod receiving_timeout_is_used_by_receive;
mod splice_connects_endpoints;
mod try_receive_up_to_does_not_combine_messages;
mod try_receive_up_to_preserves_arrival;
mod try_receive_up_to_requires_a_splitter;
mod try_receive_up_to_splits_the_front_message;
mod try_receive_with_options_ignores_timeout;
